#!/bin/bash

cd OpenMP/buildGnu/
make clean; make -j;
../runTest.sh gnu
cd ../../MPI/buildGnu/
make clean; make -j;
../runTest.sh gnu

#cd ../../MPI_sync/buildGnu/
##make clean; make -j;
#../runTest.sh gnu

#cd ../../MPI_fence/buildGnu/
##make clean; make -j;
#../runTest.sh gnu


cd ../../
source setIcc intel64; source setImpi

cd OpenMP/buildIntel/
make clean; make -j;
../runTest.sh intel
cd ../../MPI/buildIntel/
make clean; make -j;
../runTest.sh intel

#cd ../../MPI_sync/buildIntel/
##make clean; make -j;
#../runTest.sh intel
#cd ../../MPI_fence/buildIntel/
##make clean; make -j;
#../runTest.sh intel


cd ../../
source setPgi 18.3; source setPgiMpi 18.3

cd OpenMP/buildPgi/
make clean; make -j;
../runTest.sh pgi
cd ../../MPI/buildPgi/
make clean; make -j;
../runTest.sh pgi

#cd ../../MPI_sync/buildPgi/
##make clean; make -j;
#../runTest.sh pgi

#cd ../../MPI_fence/buildPgi/
##make clean; make -j;
#../runTest.sh pgi

